services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: cactus_db
      POSTGRES_USER: cactus_user
      POSTGRES_PASSWORD: cactus_pass
    ports:
      - "5433:5433"

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/cactus_db